<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Utils\\' => array($baseDir . '/Utils'),
    'Tonic\\' => array($vendorDir . '/peej/tonic'),
    'Symfony\\Component\\Console\\' => array($vendorDir . '/symfony/console'),
    'Models\\' => array($baseDir . '/Models'),
    'Controllers\\' => array($baseDir . '/Controllers'),
    'Config\\' => array($baseDir . '/Config'),
);
